/* ==================================================================
 * This confidential and proprietary software may be used only as
 * authorized by a licensing agreement from Quanta Computer Inc.
 *
 * (C) COPYRIGHT Quanta Computer Inc. ALL RIGHTS RESERVED
 *
 * ==================================================================
 * ------------------------------------------------------------------
 *  Date    :
 *  Version :
 *  Author  : Tim Hsieh (tim.hsieh@quantatw.com)
 *  Purpose :
 *  =================================================================
 */


#ifndef _RESTERRORCODE_H
#define _RESTERRORCODE_H

/*
 */
//v2 definition
enum RestErrorCode {
  EC_100_RESERVED = 0x100,
  EC_101_INVALID_API_REQUEST,
  EC_102_INCOMPATIBLE_API,
  EC_103_METHOD_NOT_ALLOWED,
  EC_104_CATEGORY_NOT_FOUND,
  EC_105_INVALID_JSON_FORMAT,
  EC_106_COLLECTION_NOT_FOUND,
  EC_107_RESOURCE_ID_NOT_FOUND,
  EC_108_INVALID_PARAMETERS,
  EC_109_MISSING_MANDATORY_PARAMETERS,
  EC_110_RESOURCE_NOT_ENOUGH,
  EC_120_UNAUTHORIZED,
  EC_121_FORBIDDEN,
  EC_200_DEVICE_ERROR = 0x200,
  EC_201_DEVICE_SYSINFO_ERROR,
  EC_202_DEVICE_NVRAM_NOT_FOUND,
  EC_203_DEVICE_MAXIMUM_TICKET,
  EC_300_VIDEO_ERROR = 0x300,
  EC_301_VIDEO_DEVICE_NOT_FOUND,
  EC_302_VIDEO_CAPTURE_CONTROL_ERROR,
  EC_303_VIDEO_STREAM_CONTROL_ERROR,
  EC_304_VIDEO_INVALID_RESOLUTION,
  EC_305_VIDEO_INVALID_FRAME_RATE,
  EC_306_VIDEO_INVALID_BITRATE,
  EC_307_VIDEO_INVALID_CAPTURE_FILTERS,
  EC_308_VIDEO_IO_CONTROL_ERROR,
  EC_309_NVRAM_ACCESS_ERROR, // jennifer : this is temporarily defined
  EC_400_AUDIO_ERROR = 0x400,
  EC_401_MIC_DEVICE_NOT_FOUND,
  EC_402_SPEAKER_DEVICE_NOT_FOUND,
  EC_403_SPEAKER_PLAYING,
  EC_404_SPEAKER_FILE_NOT_FOUND,
  EC_405_SPEAKER_DEVICE_PLAY,
  EC_406_SPEAKER_LINK_STREAM,
  EC_407_SPEAKER_NOT_PLAYING,
  EC_500_RECORD_ERROR = 0x500,
  EC_600_IO_ERROR = 0x600,
  EC_601_IO_GPIO_ERROR,
  EC_602_IO_GPIO_DEVICE_NOT_FOUND,
  EC_603_IO_GPIO_DEVICE_CONTROL_ERROR,
  EC_604_IO_PT_ERROR,
  EC_605_IO_PT_DEVICE_NOT_FOUND,
  EC_606_IO_PT_DEVICE_CONTROL_ERROR,
  EC_607_IO_PIR_DEVICE_NOT_FOUND,
  EC_608_IO_PT_UNSUPPORTED,
  EC_609_IO_PT_REACH_MAX_TAG,
  EC_700_SERVICE_ERROR = 0x700,
  EC_701_STREAM_NOT_FOUND,
  EC_702_AIRPORT_NOT_FOUND,
  EC_703_STREAM_LIVED,
  EC_704_WEBSOCKET_UNSUPPORTED,
  EC_705_TOKEN_EXCEED,
  EC_800_EVENT_ERROR = 0x800,
  EC_801_MIC_DEVICE_NOT_FOUND,
  EC_802_OOR,
  EC_803_HANDLER_NOT_FOUND,
  EC_804_EVENT_IO_PIR_DEVICE_NOT_FOUND,
  EC_900_NETWORK_ERROR = 0x900,
  EC_901_NETWORK_INTERFACE_NOT_FOUND,
};

enum RestHTTPCode {
  HC_000_RESERVED = 0,
  HC_001_IGNORE,
  // Informational 1xx
  HC_100_CONTINUE_= 100,
  HC_101_SWITCHING_PROTOCOLS,
  //_SUCCESSFUL_2XX
  HC_200_OK = 200,
  HC_201_CREATED,
  HC_202_ACCEPTED,
  HC_203_NONAUTHORITATIVE_INFORMATION,
  HC_204_NO_CONTENT,
  HC_205_RESET_CONTENT,
  HC_206_PARTIAL_CONTENT,
  //_REDIRECTION_3XX
  HC_300_MULTIPLE_CHOICES = 300,
  HC_301_MOVED_PERMANENTLY,
  HC_302_FOUND,
  HC_303_SEE_OTHER,
  HC_304_NOT_MODIFIED,
  HC_305_USE_PROXY,
  HC_306_UNUSED,
  HC_307_TEMPORARY_REDIRECT,
  //_CLIENT_ERROR_4XX
  HC_400_BAD_REQUEST = 400,
  HC_401_UNAUTHORIZED,
  HC_402_PAYMENT_REQUIRED,
  HC_403_FORBIDDEN,
  HC_404_NOT_FOUND,
  HC_405_METHOD_NOT_ALLOWED,
  HC_406_NOT_ACCEPTABLE,
  HC_407_PROXY_AUTHENTICATION_REQUIRED,
  HC_408_REQUEST_TIMEOUT,
  HC_409_CONFLICT,
  HC_410_GONE,
  HC_411_LENGTH_REQUIRED,
  HC_412_PRECONDITION_FAILED,
  HC_413_REQUEST_ENTITY_TOO_LARGE,
  HC_414_REQUEST_URI_TOO_LONG,
  HC_415_UNSUPPORTED_MEDIA_TYPE,
  HC_416_REQUESTED_RANGE_NOT_SATISFIABLE,
  HC_417_EXPECTATION_FAILED,
  //_SERVER_ERROR_5XX
  HC_500_INTERNAL_SERVER_ERROR = 500,
  HC_501_NOT_IMPLEMENTED,
  HC_502_BAD_GATEWAY,
  HC_503_SERVICE_UNAVAILABLE,
  HC_504_GATEWAY_TIMEOUT,
  HC_505_HTTP_VERSION_NOT_SUPPORTED
};

#endif /* _RESTERRORCODE_H */
